// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0uX8AilgyhI_Hc_B6Y78VZZLmNbc-hQ',
    appId: '1:657891757060:web:558fdbaafc2aec2255b951',
    messagingSenderId: '657891757060',
    projectId: 'genshin-import-c716b',
    authDomain: 'genshin-import-c716b.firebaseapp.com',
    storageBucket: 'genshin-import-c716b.firebasestorage.app',
    measurementId: 'G-VFYL2JDTJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Elfi2XUbXwIvFxQ_nj2LDi1ubaL0Vjg',
    appId: '1:657891757060:android:4b1eb5fbc1aa23f155b951',
    messagingSenderId: '657891757060',
    projectId: 'genshin-import-c716b',
    storageBucket: 'genshin-import-c716b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0uX8AilgyhI_Hc_B6Y78VZZLmNbc-hQ',
    appId: '1:657891757060:web:44d6ddbeef53485255b951',
    messagingSenderId: '657891757060',
    projectId: 'genshin-import-c716b',
    authDomain: 'genshin-import-c716b.firebaseapp.com',
    storageBucket: 'genshin-import-c716b.firebasestorage.app',
    measurementId: 'G-6NELP9DXR6',
  );
}
